http:
  middlewares:
    forward-auth:
      forwardAuth:
        address: "http://127.0.0.1:8010/auth/verify"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-User-Id"
          - "X-User-Role"
          - "X-Username"

    auth-public:
      stripPrefix:
        prefixes: []
