service:
  name: polystrategy-strategy-sweep
  port: 8003

consul:
  tags:
    - "traefik.enable=true"
    - "traefik.http.routers.polystrategy-strategy-sweep.rule=PathPrefix(`/api/strategy`)"
    - "traefik.http.routers.polystrategy-strategy-sweep.entrypoints=web"
    - "traefik.http.routers.polystrategy-strategy-sweep.middlewares=forward-auth@file"
