entryPoints:
  web:
    address: ":8000"

api:
  dashboard: true
  insecure: true

providers:
  consulCatalog:
    endpoint:
      address: "http://127.0.0.1:8500"
    exposedByDefault: false
    prefix: "traefik"
    connectByDefault: false

  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO

accessLog: {}
